import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @serwist/next at build time.
    "public/sw.js",
    "public/swe-worker-*.js",
    "public/workbox-*.js",
  ]),
  {
    // The experimental React Compiler diagnostics (shipped in eslint-plugin-react-hooks v6)
    // flag idiomatic patterns we use intentionally and aren't running the compiler:
    // dynamic icon lookup from a registry, next-themes mount flag, on-mount data fetch.
    // The classic, high-value hook rules (rules-of-hooks, exhaustive-deps) stay enabled.
    rules: {
      "react-hooks/static-components": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
